<a href="https://colab.research.google.com/github/AliRizvi14/Machine_Learning/blob/main/KFold_cross.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [34]:
iris=load_iris()

In [35]:
#Logistic Regression
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [36]:
np.average(l_scores)

0.9733333333333334

In [31]:
#Decision Tree
D_score=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
D_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [32]:
np.average(D_score)

0.9666666666666668

In [19]:
#Support Vector Machine
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [21]:
np.average(s_scores)

0.9666666666666666

In [22]:
#Random Forest
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [23]:
np.average(r_scores)

0.9600000000000002